const FakeData = [
  {
    id: 1,
    name: "ABC Ventures",
    location: "Mumbai",
    investment_focus: ["Technology", "Healthcare"],
    investment_amount: "10000000",
    contact: {
      email: "abcventures@example.com",
      phone: "+91 1234567890",
    },
  },
  {
    id: 2,
    name: "XYZ Capital",
    location: "Bangalore",
    investment_focus: ["E-commerce", "Consumer Goods"],
    investment_amount: "5000000",
    contact: {
      email: "xyzcapital@example.com",
      phone: "+91 9876543210",
    },
  },
  {
    id: 3,
    name: "PQR Holdings",
    location: "New Delhi",
    investment_focus: ["Renewable Energy", "Infrastructure"],
    investment_amount: "20000000",
    contact: {
      email: "pqrholdings@example.com",
      phone: "+91 9999999999",
    },
  },
  {
    id: 4,
    name: "TechFund India",
    location: "Hyderabad",
    investment_focus: ["Technology", "Software"],
    investment_amount: "15000000",
    contact: {
      email: "techfund@example.com",
      phone: "+91 7777777777",
    },
  },
  {
    id: 5,
    name: "HealthCare Capital",
    location: "Chennai",
    investment_focus: ["Healthcare", "Biotechnology"],
    investment_amount: "12000000",
    contact: {
      email: "healthcarecapital@example.com",
      phone: "+91 8888888888",
    },
  },
  {
    id: 6,
    name: "GreenTech Ventures",
    location: "Pune",
    investment_focus: ["Renewable Energy", "Clean Technology"],
    investment_amount: "18000000",
    contact: {
      email: "greentech@example.com",
      phone: "+91 6666666666",
    },
  },
  {
    id: 7,
    name: "RealEstate Investments Ltd.",
    location: "Mumbai",
    investment_focus: ["Real Estate", "Property Development"],
    investment_amount: "20000000",
    contact: {
      email: "realestate@example.com",
      phone: "+91 7777777777",
    },
  },
  {
    id: 8,
    name: "FoodTech Capital",
    location: "Bangalore",
    investment_focus: ["Food and Beverage", "Food Delivery"],
    investment_amount: "10000000",
    contact: {
      email: "foodtech@example.com",
      phone: "+91 8888888888",
    },
  },
  {
    id: 9,
    name: "Fashion Ventures",
    location: "New Delhi",
    investment_focus: ["Fashion", "Apparel"],
    investment_amount: "15000000",
    contact: {
      email: "fashionventures@example.com",
      phone: "+91 6666666666",
    },
  },
  {
    id: 10,
    name: "AgriTech Investments",
    location: "Chennai",
    investment_focus: ["Agriculture", "Agrochemicals"],
    investment_amount: "12000000",
    contact: {
      email: "agritech@example.com",
      phone: "+91 9999999999",
    },
  },
  {
    id: 11,
    name: "CleanEnergy Fund",
    location: "Hyderabad",
    investment_focus: ["Clean Energy", "Sustainability"],
    investment_amount: "18000000",
    contact: {
      email: "cleanenergy@example.com",
      phone: "+91 5555555555",
    },
  },
  {
    id: 12,
    name: "Education Capital",
    location: "Pune",
    investment_focus: ["Education", "EdTech"],
    investment_amount: "13000000",
    contact: {
      email: "educationcapital@example.com",
      phone: "+91 7777777777",
    },
  },
  {
    id: 13,
    name: "Financial Services Fund",
    location: "Mumbai",
    investment_focus: ["Financial Services", "Fintech"],
    investment_amount: "17000000",
    contact: {
      email: "financialservices@example.com",
      phone: "+91 8888888888",
    },
  },
  {
    id: 14,
    name: "MediaTech Ventures",
    location: "Bangalore",
    investment_focus: ["Media", "Entertainment"],
    investment_amount: "11000000",
    contact: {
      email: "mediatech@example.com",
      phone: "+91 9999999999",
    },
  },
  {
    id: 15,
    name: "Logistics Investments",
    location: "New Delhi",
    investment_focus: ["Logistics", "Supply Chain"],
    investment_amount: "16000000",
    contact: {
      email: "logistics@example.com",
      phone: "+91 5555555555",
    },
  },
  {
    id: 16,
    name: "AI Venture Partners",
    location: "Chennai",
    investment_focus: ["Artificial Intelligence", "Machine Learning"],
    investment_amount: "14000000",
    contact: {
      email: "aiventure@example.com",
      phone: "+91 6666666666",
    },
  },
];
